// DO NOT MODIFY THIS FILE, IT WILL BE OVERRIDE!!!
#ifndef _KENDRYTE_IDE_FLASH_MANGER_OUT_H
#define _KENDRYTE_IDE_FLASH_MANGER_OUT_H

#define KMODEL_START 0x700000
#define KMODEL_END 0x84A000
#define KMODEL_SIZE 1351592

#endif // _KENDRYTE_IDE_FLASH_MANGER_OUT_H

